config/routes.rb
Rails.application.routes.draw do
  resources :friend_requests
  devise_for :users, controllers: {
    #sessions: 'user/sessions'
    registrations: 'users/registrations',
    omniauth_callbacks: 'callbacks'
  }


  root 'static_pages#home'
  resources :users
  resources :friendships
  resources :friend_requests
  resources :notifications
  resources :posts
  resources :comments
  resources :likes
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <span class="notice"><%= notice %></span>
    <% end %>
    <% if alert %>
      <span class="alert"><%= alert %></span>
    <% end %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-static-top main-navigation p-2">
      <%= link_to 'Facebook Clone', root_path, class: 'navbar-brand'%>
      <button 
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#toggleMobileMenu"
        aria-controls="toggleMobileMenu"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="toggleMobileMenu">
        <% if user_signed_in? %>
          <ul class="navbar-nav ms-auto">
            <li>
              <%= link_to 'Notifications', notifications_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to 'Users', users_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to 'Friend Requests', friend_requests_path, class: "nav-link" %>
            </li>
            <li>
                <%= link_to 'View Profile', current_user, class: 'nav-link' %>
            </li>
            <li>
                <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %>
            </li>
            <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>
    
    <%= yield %>
  </body>
</html> 